services:
  starline-stock:
    build:
      context: ../docker/php
      dockerfile: Dockerfile
    container_name: starline-stock
    restart: always
    volumes:
      - ./index.php:/var/www/html/index.php
    networks:
      - starline-network

  nginx:
    image: nginx:latest
    container_name: starline-stock-nginx
    ports:
      - "3001:80"
    volumes:
      - ../docker/ngnix/conf.d/starline-stock.conf:/etc/nginx/conf.d/default.conf # Corrected the mount path to avoid conflicts
      - ./index.php:/var/www/html/index.php
    depends_on:
      - starline-stock
    networks:
      - starline-network

networks:
  starline-network:
    external: true