services:
  starline-stock:
    build:
      context: ../../docker/php
      dockerfile: Dockerfile
    container_name: starline-stock
    restart: always
    ports:
      - "3001:80"
    volumes:
      - ./index.php:/var/www/html/index.php
    networks:
      - starline-network

networks:
  starline-network:
    external: true