services:
  starline:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: starline
    restart: always
    ports:
      - "3000:3000"
    networks:
      - starline-network

networks:
  starline-network:
    external: true